### ISSUE TITLE
Make setting for wp_post_status preference when videos are pulled from services

### ISSUE THREAD

**Issue by nimmolo** [silviapfeiffer/external-videos#13]
Currently, when videos are pulled from the hosting services to the WP instance, they are automatically published. 

However, at a service with higher privacy like Vimeo, users and others can view draft videos that are not ready for publication. These videos would still appear in an authenticated request to the user's upload channel and be published on WP - not ideal. 

The proposed setting would govern whether posts pulled in by the cron job, or otherwise, are automatically published, or set to draft, pending, or private.

**Comment by nimmolo** [comment]
Delirious. Forgot this exists already

**Comment by silviapfeiffer** [comment]
That's what issue tracking is for! :-)
Is it in the FAQ though?

**Comment by nimmolo** [comment]
No - correcting that now. 
Should readme.md be the same as readme.txt?
