### ISSUE TITLE
Embed and fetch fixes

### ISSUE THREAD

**Issue by nimmolo** [silviapfeiffer/external-videos#14]
Need to sanitize video post data in the `SP_EV_Admin::save_video()` function prior to saving video posts. Also need to change this function to use the `embed_url` as the video's URL in post content, rather than the `video_url` (for viewing on host). The latter works as an embed url on some hosts, but not on others. I believe the embed url will always work if the format is correct.

In the host classes fetch loops I would like to break out the $video array standardization functions into separate functions (`compose_video($vid)`) so they are easier to read and maintain.

The upcoming "Media Explorer" extensions will need analagous functions which can be defined in the host classes at a later time.

**Comment by silviapfeiffer** [comment]
OK, I've just pushed a new release to wordpress - probably worth testing, just in case.

**Comment by silviapfeiffer** [comment]
<img width="1047" alt="screen shot 2017-01-14 at 8 48 27 am" src="https://cloud.githubusercontent.com/assets/94913/21946834/460f32d4-da36-11e6-8290-88174e3c7e6f.png">

Well, it seems to cause trouble on my Website

**Comment by nimmolo** [comment]
???!!! oh wow. I just woke up here, was up til 3am workin on it. 

Never saw this kind of thing before, though, that seems like maybe a cache error? It's a linux install? No js? Also, I wonder which version of PHP, mySQL, etc.

**Comment by silviapfeiffer** [comment]
Notice how it's version 4.3.7 - I just upgraded and it's fine now. Need to be aware of this though.

**Comment by silviapfeiffer** [comment]
<img width="778" alt="screen shot 2017-01-14 at 8 55 00 am" src="https://cloud.githubusercontent.com/assets/94913/21947050/2c24bc26-da37-11e6-8d09-cf3261111109.png">
I still see this when updating videos .. have to investigate

**Comment by nimmolo** [comment]
This is the kind of "unwrapped" admin notice i was getting last night before i cleared the errors. Thought it was fixed :-(... Sad to see it again!

**Comment by silviapfeiffer** [comment]
FWIW it works on my local site, so I don't know why it wouldn't in the released version.

**Comment by nimmolo** [comment]
Hm and i remember there was that github syncing question before. Maybe try to re-push it to SVN, after you're sure it's the working version?

**Comment by silviapfeiffer** [comment]
Do you have a production site with external-videos on it that you can test on also?

**Comment by silviapfeiffer** [comment]
Your last commit is definitely there https://github.com/silviapfeiffer/external-videos/pull/12/commits/e0c6571ea1650e26d9650fcdb3c259d67c162637  - you can check here https://plugins.svn.wordpress.org/external-videos/tags/1.0/

**Comment by silviapfeiffer** [comment]
OK, it had something to do with the existing youtube video credentials I had already stored. After removing the account and re-adding it, it now works just fine.

**Comment by silviapfeiffer** [comment]
I'll write a blog post about it - nice work and congratulations on publishing it - is this your first wordpress plugin?

**Comment by silviapfeiffer** [comment]
http://gingertech.net/2017/01/14/annual-release-of-external-videos-plugin-weve-hit-v1-0/

**Comment by nimmolo** [comment]
Thanks - yes it is my first. 

With the issue you reported I'm thinking, maybe new issue and PR. I'll add an `isset` check to each existing "authors" array key, to be sure they're there and set them if not. Similar to the options init.

This could also throw an error on the settings screen to tell people to update their author settings with missing keys (different per host, of course)

**Comment by nimmolo** [comment]
re: production site
yes I do have it up on the [Kiteboat](https://project.kiteboat.com) site, with Vimeo and Youtube accounts

**Comment by nimmolo** [comment]
phooey! i named the plugin repo icons wrong :-/ . The svg is right... but it does not seem to take [precedence over the pngs as anticipated](https://make.wordpress.org/plugins/2014/08/21/plugin-icons/).  i guess the icons will have to wait for 1.1!      that'll motivate me

**Comment by silviapfeiffer** [comment]
https://project.kiteboat.com/external-videos/ 404s

**Comment by nimmolo** [comment]
ah yes - they use the slug rewrite and that's a hard coded link. 
I just fixed it 

But maybe i also need to do a PR for "Post Type Archive Link" plugin which isn't working :-)

**Comment by silviapfeiffer** [comment]
Nice! Sure, I'll do v1.1 tomorrow if necessary
