### ISSUE TITLE
New Vimeo API

### ISSUE THREAD

**Issue by nimmolo** [silviapfeiffer/external-videos#4]
Hi Silvia,

Looks like vimeo has deprecated the" Vimeo Advanced API" - check [here](https://github.com/vimeo/vimeo-php-lib). This could be the reason for the video feed not updating from Vimeo.

I'm looking into making their API work with the plugin. Let me know if you're already working on it, otherwise I'll proceed.

**Comment by silviapfeiffer** [comment]
Go ahead - pull requests welcome!

**Comment by nimmolo** [comment]
Thanks Silvia. Quick question - reading thru Vimeo API docs now. Terminology is a bit different...
Do their "Client ID" and "Client Secret" correspond to developer_key and secret_key in the plugin settings, respectively?

**Comment by silviapfeiffer** [comment]
Yes. Note that there's an old vimeo_library.php file in the repo which you will want to replace with a new library from vimeo.

**Comment by nimmolo** [comment]
Thanks - working with the new library now. Going through all the parameters to be sure the API call is getting the right ingredients - some things have definitely changed. For example there's no function "call" anymore...

**Comment by nimmolo** [comment]
silvia -
dammit! :) How do I overwrite my fork with your current master from within the browser interface?

**Comment by silviapfeiffer** [comment]
What are you trying to do? You might need command line  git commands... but it sounds to me like you created a fork and want to undo some commits?

**Comment by nimmolo** [comment]
oh - i had forked from version 0.25 a few months ago, and since then you merged my pull request. For this new fork i just wanted to start from your current version. 

What i did just now is delete my repository and reclone from your master. But in the future I'd like to know how to keep my clone up to date, so i'm not constantly deleting it

**Comment by nimmolo** [comment]
Also - the current problem was simply the formation of an array_merge.

It should be 

    $new_videos = array_merge($new_videos, $videos);
    return $new_videos;

otherwise the array_merge is not assigned to $new_videos.

I'm still working on the new vimeo API version. The GET request is formed very differently.

**Comment by nimmolo** [comment]
OK a preliminary Vimeo API version is ready to test.
1. **This version only makes authenticated calls to Vimeo,** so the author data now requires an additional predefined auth token allowing the user to embed their own videos on their own site. (If people use your plugin to embed other people's videos on their sites, it may be desirable to have the option to do unauthenticated calls - [see here](https://github.com/vimeo/vimeo.php/blob/master/README.md#generate-your-access-token).) Anyway for now, **any existing Vimeo author data must be deleted and re-entered** - currently there's no way to edit an existing author's secret keys. The new field necessary is called a **Personal access token**, in addition to the **Client ID** and **Client secret**.  I guess the plugin should check if the "Personal access token" exists for any existing Vimeo author, and throw an alert message if author data needs to be re-entered, but i haven't written that in. 
2. **The vimeo library in the plugin is modified from the stock library.** The new Vimeo php library unfortunately does not form some parts of its own requests properly, i've got an [issue open with them on github](https://github.com/vimeo/vimeo.php/issues/104). The issue: GET requests can return a huge amount of data for a huge number of videos. Vimeo recommends filtering the results, so the request only returns the fields we need. Theoretically the fields desired should be passed as a request parameter (a comma-separated string, or possibly a nested array), but whether you pass a string or an array, the parameter gets encoded incorrectly and the desired fields are not returned. I have hacked the library to simply append a correctly-formatted string of desired fields to the request after encoding, and the request works. If Vimeo repair their library i should probably un-hack ours :)
3. My client requested that the **source and author attribution** that the plugin automatically adds to post_content **be optional**, so i've made a setting option for this.

**Comment by silviapfeiffer** [comment]
Your patches landed and I will do a release today
